language: python
python:
    - "2.7"
    - "3.6"
    - "3.7"

install:
    - pip install numpy sympy pytest
    - python setup.py develop

script:
    - py.test --doctest-modules quadrature

notifications:
    email: false
